language: objective-c
script:
- xctool test -workspace DAZABTest.xcworkspace -scheme DAZABTestTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;
install:
- pod install
after_success: slather